name: delete old unused container images
on:
  schedule:
    - cron: "0 13 * * 1" 
    # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  list_package_info:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.cleanup_packages }}
          ORG: ${{ github.repository_owner }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/$ORG/packages?package_type=container


  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: "*"      # platform, aovift, ...
          cut-off: 1w           # package versions should be older than 1 week, to be considered
          keep-n-most-recent: 3
          account: ${{ github.repository_owner }}    # Organization "cell-observatory"
          token: ${{ secrets.cleanup_packages }}
