name: 'Enforce pull request into "main" comes from "develop" Branch'

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Raise error if base branch (${{ github.base_ref }}) is 'main' and head (${{ github.head_ref }}) is not 'develop'
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from develop."
          exit 1
